DMS.Web/Models/Document.cs
using System.ComponentModel.DataAnnotations;

namespace DMS.Web.Models
{
    public class Document
    {
        public int DocumentId { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        public string Author { get; set; }
        public string Content { get; set; }
        public string FileName { get; set; }
        




    }
}

DMS.Web/ViewModels/DocumentViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace DMS.Web.viewmodel
{
    public class DocumentViewModel
    {

        [Required]
        public int DocumentId { get; set; }
        [Required(ErrorMessage = "Please enter Title.")]
        public string? Title { get; set; }
        public string? Description { get; set; }
        public string? Author { get; set; }
        public string? Content { get; set; }
        [Required(ErrorMessage = "File is required")]
        public IFormFile file { get; set; }

        public string? FileName { get; set; }

    }
}

DMS.Web/Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DMS.Web.Data;
using DMS.Web.Models;
using DMS.Web.Mapper;
using DMS.Web.viewmodel;
using Microsoft.AspNetCore.Authorization;

namespace DMS.Web.Controllers
{
    [Authorize]
    public class DocumentsController : Controller
    {
        private readonly DMSDbContext _context;

        public DocumentsController(DMSDbContext context)
        {
            _context = context;
        }

        // GET: Documents
        public async Task<IActionResult> Index()
        {
            var documentList = await _context.Documents.ToListAsync();
            var documentListVM = documentList.ToViewModel();
            if (documentListVM is not null)
            {
                return View(documentListVM);
            }
            return View(new List<DocumentViewModel>());

        }


        // GET: Documents/Create
        public IActionResult Create()
        {
            return View();
        }

       
        // POST: Documents/Create
       
        
        
        [HttpPost]
        public async Task<IActionResult> Create(DocumentViewModel documentViewModel)
        {
            if (ModelState.IsValid)
            {
                var profileRelativePath = SavefileName(documentViewModel.file);
                // Add employee record to db
                documentViewModel.FileName = profileRelativePath;

                var documentModel = documentViewModel.ToModel();
                _context.Add(documentModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(documentViewModel);
        }



        // GET: Documents/Edit/5
        public async Task<IActionResult> Edit(int id)
        {           
            var document = await _context.Documents.FindAsync(id);

            var documentViewModel = document.ToViewModel();
            
            return View(documentViewModel);
        }



        // POST: Documents/Edit/5
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(DocumentViewModel documentvm)
        {
            try
            {
                var document = documentvm.ToModel();
                _context.Update(document);

                await _context.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction(nameof(Index));
        }

        private bool DocumentExists(int documentId)
        {
            throw new NotImplementedException();
        }



        // GET: Documents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Documents == null)
            {
                return NotFound();
            }

            var document = await _context.Documents
                .FirstOrDefaultAsync(m => m.DocumentId == id);
            if (document == null)
            {
                return NotFound();
            }

            return View(document);
        }

        // POST: Documents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Documents == null)
            {
                return Problem("Entity set 'DMSDbContext.Documents'  is null.");
            }
            var document = await _context.Documents.FindAsync(id);
            if (document != null)
            {
                _context.Documents.Remove(document);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public string SavefileName(IFormFile file)
        {
            // Save image to "profiles" folder        
            var fileName = Path.GetFileNameWithoutExtension(file.FileName);  //Path.GetFileNameWithoutExtension(file.FileName)
            //var indexOfDot = fileName.LastIndexOf(".");
            //var fileExtenstion = fileName.Substring(indexOfDot);
            var fileExtenstion  = Path.GetExtension(file.FileName);
            var profileRelativePath = $"{fileName + Guid.NewGuid()}{fileExtenstion}";
            var filePath = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot/Documentupload/fileupload", profileRelativePath);

            using var stream = System.IO.File.Create(filePath);
            file.CopyTo(stream);

            return profileRelativePath;
        }

        public IActionResult Download(DocumentViewModel documentViewModel)
        {
            if (documentViewModel.FileName == null)
            {
                return Content("<script>alert('File name not present.');</script>");
            }
            var filePath = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot/Documentupload/fileupload", documentViewModel.FileName);
            //var fileStream = new FileStream(filePath, FileMode.Open, FileAccess.Read);
            byte[] bytes = System.IO.File.ReadAllBytes(filePath); 
            return File(bytes, "application/octet-stream", documentViewModel.FileName);
        }



    }
}

DMS.Web/Views/Documents/Create.cshtml
@model DMS.Web.viewmodel.DocumentViewModel

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-primary text-center">Add New Document</h1>
<br />
<br />



<form class="row" action="/Documents/Create" method="post" enctype="multipart/form-data">
    <div class="mb-3 col-6">
        <label asp-for="Title" class="form-label"></label>
        <input asp-for="Title" type="text " class="form-control " placeholder="Enter your title" />
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>
    <div class="mb-3 col-6">
        <label asp-for="Description" class="form-label"></label>
        <input asp-for="Description" type="text" class="form-control" placeholder="Give a description" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="mb-3 col-6">
        <label asp-for="Author" class="form-label"></label>
        <input asp-for="Author" type="text" class="form-control" placeholder="Provide an author" />
        <span asp-validation-for="Author" class="text-dark"></span>
    </div>
    <div class="mb-3 col-6">
        <label asp-for="Content" class="form-label"></label>
        <input asp-for="Content" type="text " class="form-control" placeholder="Give a content" />
        <span asp-validation-for="Content" class="text-danger"></span>
    </div>
    <div class="mb-3 col-12">
        <label asp-for=file class="form-label"></label>
        <input asp-for=file class="form-control" />
        <span asp-validation-for="file" class="text-danger"></span>


    </div>
    <br />
    <br />
    @*<input type="submit" value="Upload document" class="btn btn-success mb-12" />*@
    <button type="submit" class="btn btn-success"><i class="bi bi-save"></i> Save</button>




</form>

DMS.Web/Views/Documents/Delete.cshtml
@model DMS.Web.Models.Document

@{
    ViewData["Title"] = "Delete";
}

<h1 class="text-danger">Delete!!</h1>

<h3 class="text-danger">Are you sure you want to delete this document? </h3>
<div>
    <dl class="row ">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="DocumentId" />
        <input type="submit" value="Delete" class="btn btn-danger col-md-6" /> |
    </form>
</div>

DMS.Web/Views/Documents/Edit.cshtml
@model DMS.Web.viewmodel.DocumentViewModel
@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-primary">Edit Page</h1>

<div class="row">
    <div class="col-md-4 ">
        <form asp-action="Edit" asp-controller="Documents" enctype="multipart/form-data">
            <input type="hidden" asp-for="FileName" />

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DocumentId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label text-danger"></label>
                <input asp-for="Title" class="form-control" placeholder="change your document title" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label text-danger"></label>
                <input asp-for="Description" class="form-control" placeholder="Change your document designation" />
                <span asp-validation-for="Description"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label text-danger"></label>
                <input asp-for="Author" class="form-control" placeholder="change your author" />
                <span asp-validation-for="Author"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label text-danger"></label>
                <input asp-for="Content" class="form-control" placeholder="change your content" />
                <span asp-validation-for="Content"></span>
            </div>

            <div class="form-group text-center ">
                <input type="submit" value="Save changes" class="btn-success col-md-12" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DMS.Web/Views/Documents/Index.cshtml
@model List<DMS.Web.viewmodel.DocumentViewModel>

@{
    ViewData["Title"] = "Index";
}


<div class="panel panel-default border-white">
    <div class="panel-heading">
        <h3 class="panel-title text-center text-primary">List of Documents</h3>
    </div>
    <br />
    <br />

    <table class=" table table-striped table-bordered table-responsive mx-auto ">
        <thead class="bg-white bg-gradient">
            <tr>             
                <th class="text-dark">
                    @Html.DisplayName("Title")
                </th>
                <th class="text-dark">
                    @Html.DisplayName("Description")
                </th>
                <th class="text-dark">
                    @Html.DisplayName("Author")
                </th>
                <th class="text-dark">
                    @Html.DisplayName("Content")
                </th>
                <th class="text-dark col-md-1">Actions</th>
                <th class="text-dark col-md-1">Views</th>
                <th class="text-dark col-md-1">Downloads</th>
            </tr>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                 
                    @Html.HiddenFor(modelItem => item.DocumentId)
                  
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Author)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Content)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.DocumentId"><i class="bi bi-pencil-square text-success"></i></a>
                        <a asp-action="Delete" asp-route-id="@item.DocumentId"><i class="bi bi-trash3 text-danger"></i></a>
                    </td>
                    
                    <td>
                        
                        <a class="btn btn-primary" type="submit" href="~/Documentupload/fileupload/@item.FileName" target="_blank">Preview</a>



                        
                    </td>
                        

                    <td>                        
                        <form asp-controller="Documents" asp-action="Download" method="post">
                            <input type="hidden" name="FileName" value="@item.FileName" />
                            <button type="submit"class="btn btn-success">Download</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>